// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5p87B5rzBCliWH3gBK_ZeUtfrtBThRTU',
    appId: '1:777592963925:web:9598cf64472774837925dc',
    messagingSenderId: '777592963925',
    projectId: 'karconnect-2bf95',
    authDomain: 'karconnect-2bf95.firebaseapp.com',
    storageBucket: 'karconnect-2bf95.appspot.com',
    measurementId: 'G-64SFDLR6BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcFst_Iuf6wP2zo1dNa1bEkUqXfLS8pFQ',
    appId: '1:777592963925:android:e9577de28d7439827925dc',
    messagingSenderId: '777592963925',
    projectId: 'karconnect-2bf95',
    storageBucket: 'karconnect-2bf95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA69VQ3__FCPP-KNhxYkly9lTUsYgX7UPw',
    appId: '1:777592963925:ios:ca94a44d23da76707925dc',
    messagingSenderId: '777592963925',
    projectId: 'karconnect-2bf95',
    storageBucket: 'karconnect-2bf95.appspot.com',
    iosBundleId: 'com.example.karconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA69VQ3__FCPP-KNhxYkly9lTUsYgX7UPw',
    appId: '1:777592963925:ios:ca94a44d23da76707925dc',
    messagingSenderId: '777592963925',
    projectId: 'karconnect-2bf95',
    storageBucket: 'karconnect-2bf95.appspot.com',
    iosBundleId: 'com.example.karconnect',
  );
}
